language: java
jdk:
  - oraclejdk7
before_script:
  - mysql -e 'create database test_db;'
  - psql -c 'create database test_db;' -U postgres
script: mvn verify
install: true
sudo: false
cache:
  directories:
    - $HOME/.m2
